version: '3.5'

networks:
  nw:
    name: webapp_network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: /home/mcakay/data/wordpress

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - ./env
    ports:
      80:80
      443:443
    depends_on:
      - wordpress
    volumes:
      -wp:var/www/html
    network:
      nw
    restart:
      always