CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'mcakay'@'%' IDENTIFIED BY '42THGtt';
GRANT ALL PRIVILEGES ON wordpress.* TO 'mcakay'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root42THGtt';